---
layout:     post
title:      python3.8错误、调试和测试
subtitle:   Python Debug
date:       2020-6-26
author:     ErYueSheng
header-img: img/post-sample-image.jpg
catalog:    true
tags:
    - python
    - debug
---

不管写任何程序，debug是在所难免的，再天才的人物可能也会犯一些低级错误，低级到就没有想到会错的错误。

错误一般都会再运行时显示出来，而一些“运行时错误——异常”（在Python中似乎并不能说运行时错误，因为是动态语言，所有错误肯定都是运行时发现的，这里的运行时错误是指可能程序本身并没有什么问题，但是由于一些没有考虑到的外部因素导致的错误）。Python中内置了一套异常处理机制，来帮助我们进行错误处理。

调试是保证程序可以正常运行。

测试就是为了发现更多的bug，因为代码是人写的，总会出现各种各样的问题，总是有各种各样的bug。测试就是为了将尽可能的bug消灭在摇篮之中。

## 错误处理

写代码一定要认真，注意不要犯低级错误。当然现在有很多成熟的开发工具，一些简单的错误会直接被开发工具给发现。

但是一些运行时错误往往不是那么容易发现，比如在某个函数中除零了，这个时候就会引起错误。当然，这个可以通过写很多的判断语句来避免，并且常用错误码的方式来告知上层函数出错了。比如判断发现除数是0，就返回一个错误码-1。这个错误码一般都是由自己定义的，它的值一般是函数不可能出现的某个值。如果错误码没有设计好，可能就会让上层函数以为函数正确执行了，返回的结果是-1。对于高级语言，一般都会有一套错误处理机制，Python就是try...except...（finally...）。

#### try...except...（finally...）

try是尝试去运行一段程序，如果程序中发生错误，会有停止运行，抛出错误，跳转至except块完成对该错误的操作，然后跳转至finally块（可以没有）完成结尾“最后的操作”（通常是对于某些分配出去的变量，打开的数据流进行释放和回收）。如果没有错误，则不执行except部分，但是finally一样会被执行。

    try:
        print('try...')
        r = 10 / 0
        print('result:', r)
    except ZeroDivisionError as e:
        print('except:', e)
    finally:
        print('finally...')
    print('END')

可以看到，错误也有错误类型，可以通过多个except来捕捉不同类型的错误，进行不同的处理。由于多态的存在，当你捕捉一个类型错误时，会将其子类的错误都捕捉了。在except之后，finally之前，还可以添加一个else块，表示如果程序没有错误可以进行的操作。这里要注意，是没有错误，如果程序存在别的except并没有捕捉的错误，不会执行else，会将这个错误抛给上层函数。如下

    try:
        print('try...')
        r = 10 / '2'
        print('result:', r)
    except ZeroDivisionError as e:
        print('except:', e)
    else:
        print('lll')
    finally:
        print('finally...')
    print('END')

所有的错误类型都继承自BaseException，[常见的错误类型和继承关系](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)。

#### 调用栈

如果发生某一个错误，但是没有对其进行处理，则该错误会被抛给上一层函数，如果还是得不到处理，则再次抛出。知道Python解释器捕获该错误，打印错误信息，然后退出。错误总是伴随函数调用栈一层一层的抛出的，只要在合适的层次进行错误处理，则不会令整个程序终止运行。

#### 记录错误

使用try...except...可以捕获错误，让程序继续执行。另外也可以使用Python内置的logging模块来记录错误信息，甚至写到日志文件，方便排查。

    import logging
    def foo(s):
        return 10 / int(s)
    def bar(s):
        return foo(s) * 2
    def main():
        try:
            bar('0')
        except Exception as e:
            logging.exception(e)

    main()
    print('END')

#### 抛出错误

错误只是错误类型的一个实例，通过继承可以创造自己的错误类型，然后使用raise语句抛出错误。

    class FooError(ValueError):
        pass
    def foo(s):
        n = int(s)
        if n==0:
            raise FooError('invalid value: %s' % s)
        return 10 / n

在没有必要自己定义错误类型的情况下，尽量使用内置的错误类型，当except捕获到某个错误时，也可以抛出错误，然后raise后面没有错误，则抛出except捕获到的错误，也可以抛出别的错误。

## 调试

调试是写代码最痛苦的一件事情，因为你高高兴兴写完代码，一运行发现出现一堆错误，顿时心态就爆炸了。当然，已经找到的错误改一改就完事了，如果改完之后发现结果还是不对，那可能就直接上天了。

当你不知道哪些变量存在问题，这时就需要一些手段来找到出问题的地方并消灭之。

#### 简单暴力print

使用print直接将可能由问题的变量全打印出来，一眼就能看到是谁出问题了。

但是似乎太麻烦了，程序里面会充斥着满屏的print，糟心。

#### 没有啥用assert

assert断言，断言之后的条件语言为真，不然抛出AssertionError，并且可以附带信息。

    def foo(s):
        n = int(s)
        assert n != 0, 'n is zero!'
        return 10 / n
    foo('0')

assert还是会和print一样，遍布程序每个角落。但是有一点儿好是，可以在代码运行时用'-O'(杠大写欧)参数来关闭所有的assert语言，关闭之后assert可以看作pass。

#### logging

logging可以用于记录当前数据的状态生成一段文本信息，不会抛出错误。

    import logging

    s = '0'
    n = int(s)
    logging.info('n = %d' % n)
    print(10 / n)

并且logging最大的好处在于允许定义记录信息的级别，有debug、info、warning、error等，优先级依次递增。如果像上面一样不对logging进行配置，则不会看到logging信息，只有配置之后才能看到相应的记录信息。

    import logging
    logging.basicConfig(level=logging.INFO)

这里配置指定等级为INFO，这时出来info信息意外比info优先级更高的也会显示出来。这就可以很方便的查看各种优先级的记录信息。另外logging还能通过简单的配置将记录信息输出至不同的地方，比如控制台或文件中。

#### 各种调试工具、断点、IDE

使用IDE进行调试还是很方便的，打个断点，运行到断电位置停下来分析，然后一步一步运行找到出错位置。Python还有自带的pdb，感觉老难用了。

## 测试

#### 单元测试unittest

需要导入自带的unittest模块。首先编写一个单元测试类，针对每一个类进行单元测试，测试类的名字因该是'Test被测类名'，测试类应该继承unittest.TestCase类。

测试类中，应该有很多的测试函数，针对被测类中的每个函数应该有一个单独的测试函数，其函数名为'test被测函数名'，在测试函数中，定义一个被测类，并调用被测函数，使用self.assertTrue、 self.assertEqual、self.assertRaises断言结果是否正确、是否抛出相应的错误类型。

在测试类中还可以定义其他的测试函数，例如判断函数输入的完备性。测试函数都必须以test开头，不然在单元测试时不会被执行。

在文件的最后加上

    if __name__ == '__main__':
    unittest.main()

直接运行该脚本，即可完成相应的测试。

另外，在单元测试中，还有两个特殊函数**setUp**和**tearDown**，这两个函数会分别在测试函数执行之前和之后被执行，借助这两个函数可以省去很多在每个测试函数中都会出现的重复代码。

#### 文档测试doctest

对于一个函数，通常会根据其注释生成相应的帮助文档，在注释中一般会包含相应的范例（期望的输入和输出）。doctest文档测试，即是读取注释中的实例代码进行运行再与期望输出进行比较。这里要求注释中的范例严格按照Python交互式命令行的输入输出来书写。

    def abs(n):
        '''
        Function to get absolute value of number.
        Example:
        >>> abs(1)
        1
        >>> abs(-1)
        1
        >>> abs(0)
        0
        '''
        return n if n >= 0 else (-n)

对于一个类，同样可以用这样的交互式命令行书写相应的期望输入和期望输出。最后使用doctest完成文档测试

    if __name__=='__main__':
        import doctest
        doctest.testmod()

如果没有任何输出，则表示文档测试通过。

>20200707
    